version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: nest-backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: always
